version: "3"
services: 
  mysql_college:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - mysql_college:/var/lib/mysql


volumes:
  mysql_college: 
    driver: local