version: '3'
services: 
  # mongo service
  mongodb:
    image: mongo
    ports: 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes: 
      - nwrd-db-data:/data/db
  # mongo gui
  mongo-express: 
    image: mongo-express
    ports: 
      - 8081:8081
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on: 
      - mongodb
  # mysql service
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - nwrd-db-data:/var/lib/mysql
  # mysql visualizer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

      

volumes:
  nwrd-db-data:
    driver: local
  
