version: "3"
services: 
  mysql_college:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: passwd
    volumes:
      - nwrd_my:/var/lib/mysql


volumes:
  nwrd_my: 
    driver: local
