# - nwrd-mongo-data:/data/db
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27018:27017
    volumes:
      - nwrd-mongo-data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8099:8081
    depends_on:
      - mongodb

volumes:
  nwrd-mongo-data:
