# - nwrd-mongo-data:/data/db
version: "3.1"

services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - nwrd-redis-data:/data/db

volumes:
  nwrd-redis-data:
