version: "3.1"

services:
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6380:6379
    volumes:
      - nwrd-nweets-redis-data:/data/redis

  mongo:
    image: mongo
    restart: always
    ports:
      - 27019:27017
    volumes:
      - nwrd-nweets-redis-data:/data/mongo
volumes:
  nwrd-nweets-redis-data:
